name: Track Dev Functions

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  track:
    name: Extract and Track Functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew build

      - name: Generate Dokka docs
        run: ./gradlew dokkaHtml

      - name: Install Python dependencies
        run: pip3 install beautifulsoup4

      - name: Extract function-level changes
        id: extract_functions
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          COMMIT_DATE=$(git show -s --format=%ci $COMMIT_SHA)
          OUTPUT="function_change_log.md"

          echo "| Function Name | Status | Commit SHA | Date |" > $OUTPUT
          echo "|---------------|--------|------------|------|" >> $OUTPUT

          # Get diff between HEAD and previous commit
          git diff HEAD~1 HEAD -- '*.kt' '*.java' > changes.diff || true

          # Grep added, deleted, or changed function definitions (basic heuristic)
          grep -E '^[+-].*(fun |void |public |private |protected).*?\(.*?\)' changes.diff | while read -r line; do
            FUNC_LINE=$(echo "$line" | sed -E 's/^[+-]//' | sed -E 's/\s+/ /g')
            FUNC_NAME=$(echo "$FUNC_LINE" | sed -E 's/.*(fun|void)\s+([a-zA-Z0-9_]+).*/\2/')

            if [[ "$line" == +* ]]; then
              STATUS="new"
            elif [[ "$line" == -* ]]; then
              STATUS="deleted"
            fi

            echo "| $FUNC_NAME | $STATUS | $COMMIT_SHA | $COMMIT_DATE |" >> $OUTPUT
          done

      - name: Upload function log artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-change-log-${{ github.sha }}
          path: function_change_log.md
